# Generated by Django 3.1.6 on 2021-02-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, verbose_name='Уникальное название для URL')),
                ('name', models.CharField(max_length=256, verbose_name='Название видео')),
                ('body', models.CharField(max_length=1024, verbose_name='Краткое описание видео')),
                ('url_video', models.URLField(max_length=256, verbose_name='Ссылка на видео')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Время создания поста с видео')),
            ],
        ),
    ]
