# Generated by Django 3.1.6 on 2021-03-30 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=256, verbose_name='ФИО игрока')),
                ('photo', models.FileField(upload_to='player_photos/', verbose_name='Фото игрока')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Время создания игрока')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название команды')),
                ('logo', models.FileField(upload_to='team_logos/', verbose_name='Логотип команды')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Время создания команды')),
            ],
        ),
        migrations.CreateModel(
            name='TeamStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Команда')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.player', verbose_name='Игрок')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Команда в которой состоит игрок'),
        ),
        migrations.CreateModel(
            name='PastGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата проведения матча')),
                ('time', models.TimeField(verbose_name='Время проведения матча')),
                ('address', models.CharField(max_length=256, verbose_name='Место проведения матча')),
                ('result', models.CharField(max_length=32, verbose_name='Результат матча')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Время создания записи')),
                ('team_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pg_team_one', to='teams.team', verbose_name='Первая команда')),
                ('team_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pg_team_two', to='teams.team', verbose_name='Вторая команда')),
            ],
        ),
    ]
