# Generated by Django 3.1.6 on 2021-02-27 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_pastgamestat_playerstat_teamstat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastgame',
            name='date',
            field=models.DateField(verbose_name='Дата проведения матча'),
        ),
    ]
