# Generated by Django 3.1.6 on 2021-02-27 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcominggame',
            name='date',
            field=models.DateField(verbose_name='Дата проведения матча (дд.мм.гггг)'),
        ),
        migrations.AlterField(
            model_name='upcominggame',
            name='time',
            field=models.TimeField(verbose_name='Время проведения матча (чч:мм)'),
        ),
    ]
