version: '3.3'

services:
  app:
    build: .
    command: gunicorn bandyplace.wsgi:application --bind 0:8000
    volumes:
      - staticfile:/usr/src/app/static
      - mediafile:/usr/src/app/media
    expose:
      - 8000
    env_file:
      - ./bandyplace/.env
    restart: always
    depends_on:
      - db
  db:
    image: postgres:12
    expose:
      - 5432
    volumes:
      - ../pg_data:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_DB=bandyplace
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - PGDATA=/var/lib/postgresql/data/pgdata
  nginx:
    build: nginx/.
    volumes:
      - staticfile:/usr/src/app/static
      - mediafile:/usr/src/app/media
    ports:
      - 1337:80
    depends_on:
      - app

volumes:
  staticfile:
    driver: local
  mediafile:
    driver: local