# Generated by Django 3.1.6 on 2021-03-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(max_length=8192, verbose_name='Основной текст новости'),
        ),
    ]
