# Generated by Django 3.1.6 on 2021-02-27 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(max_length=4096, verbose_name='Основной текст новости'),
        ),
    ]
