# Generated by Django 3.1.6 on 2021-02-27 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210227_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=64, unique=True, verbose_name='Уникальное название для URL'),
        ),
    ]
