# Generated by Django 3.1.6 on 2021-03-30 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название товара')),
                ('description', models.TextField(max_length=256, verbose_name='Характеристики/описание товара')),
                ('url_shop', models.URLField(max_length=256, verbose_name='Ссылка на товар')),
                ('price', models.PositiveIntegerField(verbose_name='Стоимость товара')),
                ('image', models.FileField(upload_to='shop_images/', verbose_name='Картинка товара')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Время создания товара')),
            ],
        ),
    ]
